apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hls-iot

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - prometheus-rules.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: hls-iot-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: hls-iot-platform
